import './globals.css'
import { Inter } from 'next/font/google'

import CentralData from './ContextApis/context';
import Nav from './components/Nav';



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My-Unshplash',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>

          <CentralData>
            <Nav />
            {children}
          </CentralData>


      </body>
    </html>
  )
}
